---
title: "CoresPlot"
author: "Balti Boix"
date: "21 de marzo de 2016"
output: html_document
---

Primero cargamos los paquetes de R que vamos a utilizar

```{r}
require(openxlsx, quietly = TRUE)
require(dplyr, quietly = TRUE)
require(ggplot2, quietly = TRUE)
require(stringr, quietly = TRUE)
require(tidyr, quietly = TRUE)
require(TTR, quietly = TRUE)
require(grid, quietly = TRUE)
require(gridExtra, quietly = TRUE)
require(forecast, quietly = TRUE)
require(plotly, quietly = TRUE)
if(!exists("plotCCAA")) source('plotCCAA.R', encoding="UTF-8")
if(!exists("plotComb")) source('plotCombustible.R', encoding="UTF-8")
```

Leemos el fichero XLS de la WEB de CORES

```{r, echo=FALSE}
download.file("http://www.cores.es/sites/default/files/archivos/estadisticas/consumos-pp-ccaa-provincias.xlsx", 
              "consumos.xlsx", mode = "wb")
df<-read.xlsx("consumos.xlsx", sheet="Consumos", startRow = 6)
df<-filter(df, Año != "")
df<-filter(df, Año > 1997 & Año < 2020)
df<-select(df, -contains("bio"))
```

Adaptamos los datos a R y calculamos la media movil a 12 meses

```{r}
df1<-mutate(df, Date = as.Date(paste(Año, Mes, "1"), "%Y %B %d"))
for(i in 5:11)  {
      df1[,i]<-round(as.numeric(as.character(df1[,i])),0)
}
df1[,5:11][is.na(df1[,5:11])]<-0
names(df1)<- str_replace_all(names(df1), "[^[:alnum:]]", "")
df1<-df1[, c(12, 1:11)]
df1$CCAA <- gsub("Total Nacional", "España", df1$CCAA)
df1<-mutate(df1, Gasolina = Gasolina97IO + Gasolina95IO + Gasolina98IO)
df1<-mutate(df1, Gasóleo = GasóleoA + GasóleoB + GasóleoC)

df1ma<-df1
df1ma<-mutate(df1ma, ind=paste0(CCAA, Provincia))
lista<-distinct(select(df1ma, ind))
for(j in 1:nrow(lista)){
      for(i in 6:14)  {
            df1ma[df1ma$ind==lista$ind[j],i]<-round(SMA(df1ma[df1ma$ind==lista$ind[j],i], n=12),0)
      }
}
df1ma<-select(df1ma, -ind)
```

```{r}
fechas<-c("2014-01-01", "end")
p<-plotCCAA("España", fechas)
```

